### ISSUE TITLE
Consider using requests' session objects to help manage authentication flow

### ISSUE THREAD

**Issue by anarchivist** [RockefellerArchiveCenter/asExportIncremental#2]
See http://www.python-requests.org/en/latest/user/advanced/#session-objects

**Comment by anarchivist** [comment]
You shoudn't have to authenticate on every request, you should retain and reuse the session token you get  back as much as you can.

**Comment by helrond** [comment]
@marktriggs suggested passing `&expiring=false` on the initial authentication request.

**Comment by anarchivist** [comment]
+1. `requests.Session()` should help you prepopulate the authN token across requests, and will use a persistent HTTP connection.
