### ISSUE TITLE
Delegate streaming of downloads to requests_toolbelt.downloadutils

### ISSUE THREAD

**Issue by anarchivist** [RockefellerArchiveCenter/asExportIncremental#3]
See http://toolbelt.readthedocs.org/en/latest/downloadutils.html

**Comment by helrond** [comment]
@anarchivist what are the benefits to doing this as opposed to what is currently happening (just chunking the file with requests)

**Comment by anarchivist** [comment]
It does the same thing - I'd say the only argument is really for code clarity.
