### ISSUE TITLE
Avoid using `id` as a variable name

### ISSUE THREAD

**Issue by anarchivist** [RockefellerArchiveCenter/asExportIncremental#4]
`id()` is reserved in Python for the identity function; see http://stackoverflow.com/questions/77552/id-is-a-bad-variable-name-in-python

**Comment by helrond** [comment]
+1 from @pobocks

**Comment by pobocks** [comment]
Suggest reopen - it's still being used as a function argument in several places (example: https://github.com/RockefellerArchiveCenter/asExportIncremental/blob/master/asExportIncremental.py#L67)
